/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vincent2b;

/**
 *
 * @author CL1-PC04
 */
public class Addition extends javax.swing.JFrame {

    /**
     * Creates new form Addition
     */
    public Addition() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNum2 = new javax.swing.JTextField();
        txtNum1 = new javax.swing.JTextField();
        lblDiff = new javax.swing.JLabel();
        lblPro = new javax.swing.JLabel();
        lblQuo = new javax.swing.JLabel();
        sum = new javax.swing.JLabel();
        btnMul = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnMain = new javax.swing.JButton();
        lblSum = new javax.swing.JLabel();
        sum2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 110, -1));
        getContentPane().add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 42, 110, -1));

        lblDiff.setText("Diff");
        getContentPane().add(lblDiff, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, -1));

        lblPro.setText("Pro");
        getContentPane().add(lblPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 110, -1));

        lblQuo.setText("Quo");
        getContentPane().add(lblQuo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, -1));

        sum.setText("Num2");
        getContentPane().add(sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        btnMul.setText("Go To  Multiplication");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });
        getContentPane().add(btnMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        btnSub.setText("Go To Subtraction");
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });
        getContentPane().add(btnSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        btnDiv.setText("Go To Division");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        btnMain.setText("Go To Main");
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lblSum.setText("Sum");
        getContentPane().add(lblSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 120, -1));

        sum2.setText("Num1");
        getContentPane().add(sum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel1.setText("Addition");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int num1 = Integer.parseInt(txtNum1.getText());
        int num2 = Integer.parseInt(txtNum2.getText());
        
        
        int add = num1 + num2 ;
        int sub = num1 - num2;
        int multi = num1 * num2;
        int division = num1 / num2;
        
        lblSum.setText("The sum is" + add);
        lblDiff.setText("The diff is" + sub);
        lblPro.setText("The product is" + multi);
        lblQuo.setText("The quotient is" + division);
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        this.dispose();
        new division().show(true);
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        this.dispose();
        new Addition().show(true);
    }//GEN-LAST:event_btnMainActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        this.dispose();
        new Subtraction().show(true);
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        this.dispose();
        new Multiply().show(true);
    }//GEN-LAST:event_btnMulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDiff;
    private javax.swing.JLabel lblPro;
    private javax.swing.JLabel lblQuo;
    private javax.swing.JLabel lblSum;
    private javax.swing.JLabel sum;
    private javax.swing.JLabel sum2;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    // End of variables declaration//GEN-END:variables
}
