/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vincent2b;

import javax.swing.JOptionPane;

/**
 *
 * @author CL1-PC07
 */
public class dasfsdf extends javax.swing.JFrame {

    /**
     * Creates new form dasfsdf
     */
    public dasfsdf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVs = new javax.swing.JButton();
        txtPlayer1 = new javax.swing.JTextField();
        txtPlayer2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("2- paper");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setText("3 - Scissors");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setText("1- Rock");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        btnVs.setText("VS");
        btnVs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVsActionPerformed(evt);
            }
        });
        getContentPane().add(btnVs, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));
        getContentPane().add(txtPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, -1));
        getContentPane().add(txtPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 170, -1));

        jLabel4.setText("Player1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel5.setText("Player2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVsActionPerformed
        int player1 = Integer.parseInt(txtPlayer1.getText());
        int player2 = Integer.parseInt(txtPlayer2.getText());

        if (player1 == 1 && player2 == 1)
        {
        JOptionPane.showMessageDialog(null,  "Draw", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 1 && player2 == 2)
        {
        JOptionPane.showMessageDialog(null,  "Player2 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 1 && player2 == 3)
        {
        JOptionPane.showMessageDialog(null,  "Player1 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 2 && player2 == 1)
        {
        JOptionPane.showMessageDialog(null,  "Player1 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 2 && player2 == 2)
        {
        JOptionPane.showMessageDialog(null,  "Draw", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }

        else if (player1 == 2 && player2 == 3)
        {
        JOptionPane.showMessageDialog(null,  "Player2 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 3 && player2 == 1)
        {
        JOptionPane.showMessageDialog(null,  "Player1 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 3 && player2 == 2)
        {
        JOptionPane.showMessageDialog(null,  "Player2", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 3 && player2 == 3)
        {
        JOptionPane.showMessageDialog(null,  "Draw", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }

        else
        {
        JOptionPane.showMessageDialog(null,  "Please input right choice", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        

    }//GEN-LAST:event_btnVsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dasfsdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dasfsdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dasfsdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dasfsdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dasfsdf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPlayer1;
    private javax.swing.JTextField txtPlayer2;
    // End of variables declaration//GEN-END:variables
}
